// Generates supabase/seed.sql from scripts/seed-data.mjs
// Usage: node scripts/generate-seed.mjs
import { writeFileSync } from "node:fs";
import { exams, subjects, questions } from "./seed-data.mjs";

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const out = [];
out.push("-- Generated by scripts/generate-seed.mjs — do not edit by hand.");
out.push("-- Sample questions are tagged source='sample'. Remove before launch:");
out.push("--   delete from public.questions where source = 'sample';");
out.push("begin;");

for (const [short, en, hi, year, order] of exams) {
  out.push(`insert into public.exams (short_name, name_en, name_hi, year, sort_order) values (${q(short)}, ${q(en)}, ${q(hi)}, ${year}, ${order}) on conflict (short_name) do nothing;`);
}

subjects.forEach(([slug, en, hi, icon, topics], i) => {
  out.push(`insert into public.subjects (slug, name_en, name_hi, icon, sort_order) values (${q(slug)}, ${q(en)}, ${q(hi)}, ${q(icon)}, ${i + 1}) on conflict (slug) do nothing;`);
  topics.forEach(([tslug, ten, thi], j) => {
    out.push(`insert into public.topics (subject_id, slug, name_en, name_hi, sort_order) select id, ${q(tslug)}, ${q(ten)}, ${q(thi)}, ${j + 1} from public.subjects where slug = ${q(slug)} on conflict (subject_id, slug) do nothing;`);
  });
});

const examYear = Object.fromEntries(exams.map(([s, , , y]) => [s, y]));
for (const x of questions) {
  if (!["A", "B", "C", "D", "E"].includes(x.ans)) throw new Error("bad answer " + x.en);
  if (!x.options.some((o) => o.key === x.ans)) throw new Error("answer not in options: " + x.en);
  out.push(`insert into public.questions (exam_id, year, subject_id, topic_id, difficulty, question_en, question_hi, options, correct_option, solution_en, solution_hi, is_dropped, is_high_priority, theme, source, created_by)
select e.id, ${examYear[x.exam]}, s.id, t.id, ${q(x.d)}, ${q(x.en)}, ${q(x.hi)}, ${q(JSON.stringify(x.options))}::jsonb, ${q(x.ans)}, ${q(x.solEn)}, ${q(x.solHi)}, ${!!x.dropped}, ${!!x.hp}, ${q(x.theme)}, 'sample', null
from public.subjects s join public.topics t on t.subject_id = s.id and t.slug = ${q(x.t)}
left join public.exams e on e.short_name = ${q(x.exam)}
where s.slug = ${q(x.s)};`);
}
out.push("commit;");
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n") + "\n");
console.log(`Wrote seed.sql: ${exams.length} exams, ${subjects.length} subjects, ${questions.length} questions (${questions.filter((x) => !x.dropped).length} live)`);
