// Seed data for the GS Hub BPSC PYQ Portal.
// Run `node scripts/generate-seed.mjs` to regenerate supabase/seed.sql.
//
// NOTE: the 30 questions below are BPSC-STYLE SAMPLES written for testing
// (source = 'sample'). They are tagged to exams only so the year filter can be
// tested — they are NOT verified previous-year questions. Delete them before
// launch:  delete from questions where source = 'sample';

export const exams = [
  ["56-59th", "56th–59th BPSC Combined Prelims", "56वीं–59वीं बीपीएससी संयुक्त प्रारंभिक", 2015, 56],
  ["60-62nd", "60th–62nd BPSC Combined Prelims", "60वीं–62वीं बीपीएससी संयुक्त प्रारंभिक", 2017, 60],
  ["63rd", "63rd BPSC Integrated Prelims", "63वीं बीपीएससी संयुक्त प्रारंभिक", 2017, 63],
  ["64th", "64th BPSC Integrated Prelims", "64वीं बीपीएससी संयुक्त प्रारंभिक", 2018, 64],
  ["65th", "65th BPSC Integrated Prelims", "65वीं बीपीएससी संयुक्त प्रारंभिक", 2019, 65],
  ["66th", "66th BPSC Integrated Prelims", "66वीं बीपीएससी संयुक्त प्रारंभिक", 2020, 66],
  ["67th", "67th BPSC Integrated Prelims", "67वीं बीपीएससी संयुक्त प्रारंभिक", 2022, 67],
  ["68th", "68th BPSC Integrated Prelims", "68वीं बीपीएससी संयुक्त प्रारंभिक", 2023, 68],
  ["69th", "69th BPSC Integrated Prelims", "69वीं बीपीएससी संयुक्त प्रारंभिक", 2023, 69],
  ["70th", "70th BPSC Integrated Prelims", "70वीं बीपीएससी संयुक्त प्रारंभिक", 2024, 70],
  ["71st", "71st BPSC Integrated Prelims", "71वीं बीपीएससी संयुक्त प्रारंभिक", 2025, 71],
];

// [slug, en, hi, icon, topics: [slug, en, hi][]]
export const subjects = [
  ["history", "History", "इतिहास", "🏛️", [
    ["ancient", "Ancient History", "प्राचीन इतिहास"],
    ["medieval", "Medieval History", "मध्यकालीन इतिहास"],
    ["modern", "Modern History", "आधुनिक इतिहास"],
    ["bihar-history", "Bihar History", "बिहार का इतिहास"],
    ["art-culture", "Art & Culture", "कला एवं संस्कृति"],
  ]],
  ["geography", "Geography", "भूगोल", "🌏", [
    ["india", "Indian Geography", "भारत का भूगोल"],
    ["world", "World Geography", "विश्व भूगोल"],
    ["bihar", "Bihar Geography", "बिहार का भूगोल"],
    ["physical", "Physical Geography", "भौतिक भूगोल"],
  ]],
  ["polity", "Polity", "राजव्यवस्था", "⚖️", [
    ["constitution", "Constitution & Preamble", "संविधान एवं प्रस्तावना"],
    ["fundamental-rights", "Fundamental Rights & Duties", "मौलिक अधिकार एवं कर्तव्य"],
    ["parliament", "Parliament & Executive", "संसद एवं कार्यपालिका"],
    ["judiciary", "Judiciary", "न्यायपालिका"],
    ["local-government", "Local Government", "स्थानीय शासन"],
  ]],
  ["economy", "Economy", "अर्थव्यवस्था", "📈", [
    ["national-income", "National Income", "राष्ट्रीय आय"],
    ["banking", "Banking & Monetary Policy", "बैंकिंग एवं मौद्रिक नीति"],
    ["fiscal-policy", "Fiscal Policy & Budget", "राजकोषीय नीति एवं बजट"],
    ["bihar-economy", "Bihar Economy", "बिहार की अर्थव्यवस्था"],
    ["bihar-budget", "Bihar Budget & Survey", "बिहार बजट एवं आर्थिक सर्वेक्षण"],
  ]],
  ["science", "General Science", "सामान्य विज्ञान", "🔬", [
    ["physics", "Physics", "भौतिकी"],
    ["chemistry", "Chemistry", "रसायन विज्ञान"],
    ["biology", "Biology", "जीव विज्ञान"],
  ]],
  ["current-affairs", "Current Affairs", "समसामयिकी", "📰", [
    ["national", "National", "राष्ट्रीय"],
    ["international", "International", "अंतरराष्ट्रीय"],
    ["science-tech", "Science & Technology", "विज्ञान एवं प्रौद्योगिकी"],
    ["sports-awards", "Sports & Awards", "खेल एवं पुरस्कार"],
  ]],
  ["bihar-special", "Bihar Special", "बिहार विशेष", "🪔", [
    ["bihar-polity", "Bihar Polity & Administration", "बिहार राजव्यवस्था एवं प्रशासन"],
    ["bihar-culture", "Bihar Culture & Festivals", "बिहार की संस्कृति एवं पर्व"],
    ["bihar-schemes", "Bihar Govt Schemes", "बिहार सरकार की योजनाएँ"],
  ]],
  ["mental-ability", "Mental Ability / Reasoning", "मानसिक क्षमता / तर्कशक्ति", "🧠", [
    ["number-series", "Number Series", "संख्या श्रृंखला"],
    ["arithmetic", "Arithmetic", "अंकगणित"],
    ["coding-decoding", "Coding–Decoding", "कूट-लेखन"],
  ]],
];

const O = (A, B, C, D, E) => [A, B, C, D, E].filter(Boolean).map((o, i) => ({ key: "ABCDE"[i], en: o[0], hi: o[1] }));
const MORE_THAN_ONE = ["More than one of the above", "उपर्युक्त में से एक से अधिक"];
const NONE = ["None of the above", "उपर्युक्त में से कोई नहीं"];
const p = (...lines) => lines.map((l) => `<p>${l}</p>`).join("");

// subject, topic, exam, difficulty, qEn, qHi, options, answer, solEn, solHi, extras
export const questions = [
  {
    s: "history", t: "ancient", exam: "56-59th", d: "easy", theme: "magadha-empire",
    en: "Who was the founder of the Mauryan Empire?",
    hi: "मौर्य साम्राज्य का संस्थापक कौन था?",
    options: O(["Bindusara", "बिंदुसार"], ["Chandragupta Maurya", "चंद्रगुप्त मौर्य"], ["Ashoka", "अशोक"], ["Bimbisara", "बिंबिसार"]),
    ans: "B",
    solEn: p("<b>Correct: (B) Chandragupta Maurya</b> — with the guidance of Chanakya (Kautilya) he overthrew the Nanda dynasty around 322 BCE and founded the Mauryan Empire with Pataliputra as capital.",
      "(A) Bindusara was his son and successor. (C) Ashoka was Bindusara's son, the third Mauryan ruler. (D) Bimbisara belonged to the earlier Haryanka dynasty of Magadha."),
    solHi: p("<b>सही उत्तर: (B) चंद्रगुप्त मौर्य</b> — चाणक्य (कौटिल्य) के मार्गदर्शन में लगभग 322 ई.पू. में नंद वंश को हराकर उन्होंने मौर्य साम्राज्य की स्थापना की; राजधानी पाटलिपुत्र थी।",
      "(A) बिंदुसार उनके पुत्र व उत्तराधिकारी थे। (C) अशोक बिंदुसार के पुत्र और तीसरे मौर्य शासक थे। (D) बिंबिसार इससे पहले के हर्यक वंश के शासक थे।"),
  },
  {
    s: "history", t: "ancient", exam: "64th", d: "medium", theme: "nalanda",
    en: "Nalanda Mahavihara was founded by which Gupta ruler?",
    hi: "नालंदा महाविहार की स्थापना किस गुप्त शासक ने की थी?",
    options: O(["Kumaragupta I", "कुमारगुप्त प्रथम"], ["Chandragupta II", "चंद्रगुप्त द्वितीय"], ["Samudragupta", "समुद्रगुप्त"], ["Skandagupta", "स्कंदगुप्त"]),
    ans: "A",
    solEn: p("<b>Correct: (A) Kumaragupta I</b> (c. 415–455 CE) is credited with founding Nalanda Mahavihara; it later received patronage from Harshavardhana and the Pala kings.",
      "(B) Chandragupta II 'Vikramaditya' is known for Kalidasa and Fa-Hien's visit. (C) Samudragupta is known for the Allahabad (Prayag) Prashasti. (D) Skandagupta is known for repelling the Hunas."),
    solHi: p("<b>सही उत्तर: (A) कुमारगुप्त प्रथम</b> (लगभग 415–455 ई.) को नालंदा महाविहार की स्थापना का श्रेय दिया जाता है; बाद में हर्षवर्धन व पाल शासकों ने इसे संरक्षण दिया।",
      "(B) चंद्रगुप्त द्वितीय 'विक्रमादित्य' कालिदास और फाह्यान की यात्रा के लिए प्रसिद्ध हैं। (C) समुद्रगुप्त प्रयाग प्रशस्ति के लिए जाने जाते हैं। (D) स्कंदगुप्त ने हूणों को पराजित किया था।"),
  },
  {
    s: "history", t: "bihar-history", exam: "66th", d: "medium", theme: "magadha-empire",
    en: "Pataliputra was made the capital of Magadha by which ruler?",
    hi: "पाटलिपुत्र को मगध की राजधानी किस शासक ने बनाया?",
    options: O(["Bimbisara", "बिंबिसार"], ["Ajatashatru", "अजातशत्रु"], ["Udayin", "उदयिन"], ["Shishunaga", "शिशुनाग"]),
    ans: "C",
    solEn: p("<b>Correct: (C) Udayin</b> (Udayabhadra), son of Ajatashatru, founded the city at the confluence of the Ganga and Son and shifted the capital from Rajgriha to Pataliputra.",
      "(A) Bimbisara ruled from Rajgriha (Girivraj). (B) Ajatashatru built a fort at Pataligrama, but did not shift the capital. (D) Shishunaga temporarily shifted the capital to Vaishali."),
    solHi: p("<b>सही उत्तर: (C) उदयिन</b> (उदयभद्र), अजातशत्रु के पुत्र, ने गंगा–सोन संगम पर नगर बसाया और राजधानी राजगृह से पाटलिपुत्र स्थानांतरित की।",
      "(A) बिंबिसार की राजधानी राजगृह (गिरिव्रज) थी। (B) अजातशत्रु ने पाटलिग्राम में दुर्ग बनवाया, पर राजधानी नहीं बदली। (D) शिशुनाग ने अस्थायी रूप से राजधानी वैशाली स्थानांतरित की।"),
  },
  {
    s: "history", t: "medieval", exam: "60-62nd", d: "easy", theme: "sher-shah",
    en: "The tomb of Sher Shah Suri is located at:",
    hi: "शेरशाह सूरी का मकबरा कहाँ स्थित है?",
    options: O(["Sasaram", "सासाराम"], ["Delhi", "दिल्ली"], ["Agra", "आगरा"], ["Chunar", "चुनार"]),
    ans: "A",
    solEn: p("<b>Correct: (A) Sasaram</b> (Rohtas district, Bihar). The red-sandstone tomb stands in the middle of an artificial lake and is a fine example of Indo-Afghan architecture.",
      "Delhi, Agra and Chunar are associated with Sher Shah's campaigns and buildings (e.g. Purana Qila in Delhi), but his tomb is in his birthplace region, Sasaram."),
    solHi: p("<b>सही उत्तर: (A) सासाराम</b> (रोहतास ज़िला, बिहार)। लाल बलुआ पत्थर से बना यह मकबरा कृत्रिम झील के बीच स्थित है और इंडो-अफ़गान स्थापत्य का उत्कृष्ट उदाहरण है।",
      "दिल्ली, आगरा और चुनार शेरशाह के अभियानों/निर्माणों (जैसे दिल्ली का पुराना किला) से जुड़े हैं, पर उनका मकबरा सासाराम में है।"),
  },
  {
    s: "history", t: "modern", exam: "63rd", d: "easy", theme: "champaran",
    en: "Who persuaded Mahatma Gandhi to come to Champaran in 1917?",
    hi: "1917 में महात्मा गांधी को चंपारण आने के लिए किसने प्रेरित किया?",
    options: O(["Rajkumar Shukla", "राजकुमार शुक्ल"], ["Dr. Rajendra Prasad", "डॉ. राजेंद्र प्रसाद"], ["Brajkishore Prasad", "ब्रजकिशोर प्रसाद"], ["Anugrah Narayan Sinha", "अनुग्रह नारायण सिन्हा"]),
    ans: "A",
    solEn: p("<b>Correct: (A) Rajkumar Shukla</b>, an indigo cultivator of Champaran, met Gandhi at the Lucknow Congress (1916) and persuaded him to see the plight of farmers under the <i>tinkathia</i> system.",
      "(B), (C) and (D) joined Gandhi during the Champaran Satyagraha as associates, but did not invite him."),
    solHi: p("<b>सही उत्तर: (A) राजकुमार शुक्ल</b> — चंपारण के नील किसान, जिन्होंने लखनऊ कांग्रेस (1916) में गांधीजी से मिलकर उन्हें <i>तिनकठिया</i> प्रथा से पीड़ित किसानों की दशा देखने के लिए राज़ी किया।",
      "(B), (C) व (D) चंपारण सत्याग्रह में गांधीजी के सहयोगी बने, पर आमंत्रण उन्होंने नहीं दिया।"),
  },
  {
    s: "history", t: "bihar-history", exam: "65th", d: "easy", theme: "1857-bihar",
    en: "Who led the Revolt of 1857 from Jagdishpur in Bihar?",
    hi: "1857 के विद्रोह में बिहार के जगदीशपुर से नेतृत्व किसने किया?",
    options: O(["Kunwar Singh", "कुँवर सिंह"], ["Pir Ali", "पीर अली"], ["Waris Ali", "वारिस अली"], ["Jitu Santhal", "जीतू संथाल"]),
    ans: "A",
    solEn: p("<b>Correct: (A) Babu Kunwar Singh</b>, the zamindar of Jagdishpur (Bhojpur), led the revolt in Bihar at about 80 years of age; 23 April is observed as 'Vijayotsav'.",
      "(B) Pir Ali led the uprising in Patna and was hanged in July 1857. (C) Waris Ali was a police jamadar in Tirhut, among the first executed in Bihar. (D) is not associated with leading 1857 in Jagdishpur."),
    solHi: p("<b>सही उत्तर: (A) बाबू कुँवर सिंह</b>, जगदीशपुर (भोजपुर) के ज़मींदार, ने लगभग 80 वर्ष की आयु में बिहार में विद्रोह का नेतृत्व किया; 23 अप्रैल 'विजयोत्सव' के रूप में मनाया जाता है।",
      "(B) पीर अली ने पटना में विद्रोह किया और जुलाई 1857 में फाँसी दी गई। (C) वारिस अली तिरहुत के पुलिस जमादार थे। (D) का जगदीशपुर के नेतृत्व से संबंध नहीं है।"),
  },
  {
    s: "history", t: "modern", exam: "68th", d: "medium", theme: "press-national-movement",
    en: `<p>Match List-I (Newspaper) with List-II (Founder/Editor):</p><table><tr><th>List-I</th><th>List-II</th></tr><tr><td>(a) Kesari</td><td>1. Surendranath Banerjee</td></tr><tr><td>(b) Harijan</td><td>2. Maulana Abul Kalam Azad</td></tr><tr><td>(c) Al-Hilal</td><td>3. M. K. Gandhi</td></tr><tr><td>(d) The Bengalee</td><td>4. B. G. Tilak</td></tr></table>`,
    hi: `<p>सूची-I (समाचार-पत्र) को सूची-II (संस्थापक/संपादक) से सुमेलित कीजिए:</p><table><tr><th>सूची-I</th><th>सूची-II</th></tr><tr><td>(a) केसरी</td><td>1. सुरेंद्रनाथ बनर्जी</td></tr><tr><td>(b) हरिजन</td><td>2. मौलाना अबुल कलाम आज़ाद</td></tr><tr><td>(c) अल-हिलाल</td><td>3. एम. के. गांधी</td></tr><tr><td>(d) द बंगाली</td><td>4. बी. जी. तिलक</td></tr></table>`,
    options: O(["a-4, b-3, c-2, d-1", "a-4, b-3, c-2, d-1"], ["a-3, b-4, c-1, d-2", "a-3, b-4, c-1, d-2"], ["a-4, b-2, c-3, d-1", "a-4, b-2, c-3, d-1"], ["a-1, b-3, c-2, d-4", "a-1, b-3, c-2, d-4"], NONE),
    ans: "A",
    solEn: p("<b>Correct: (A) a-4, b-3, c-2, d-1.</b>",
      "Kesari (Marathi, 1881) — Tilak; Harijan (1933) — Gandhi; Al-Hilal (Urdu, 1912) — Abul Kalam Azad; The Bengalee — Surendranath Banerjee. Every other code mismatches at least two pairs, so (E) is also wrong."),
    solHi: p("<b>सही उत्तर: (A) a-4, b-3, c-2, d-1.</b>",
      "केसरी (मराठी, 1881) — तिलक; हरिजन (1933) — गांधी; अल-हिलाल (उर्दू, 1912) — अबुल कलाम आज़ाद; द बंगाली — सुरेंद्रनाथ बनर्जी। अन्य सभी कूट में कम से कम दो जोड़े गलत हैं, इसलिए (E) भी गलत है।"),
  },
  {
    s: "history", t: "art-culture", exam: "64th", d: "easy", theme: "bihar-folk-art",
    en: "Madhubani painting is traditionally associated with which cultural region of Bihar?",
    hi: "मधुबनी चित्रकला परंपरागत रूप से बिहार के किस सांस्कृतिक क्षेत्र से जुड़ी है?",
    options: O(["Magadh", "मगध"], ["Mithila", "मिथिला"], ["Bhojpur", "भोजपुर"], ["Anga", "अंग"]),
    ans: "B",
    solEn: p("<b>Correct: (B) Mithila.</b> Madhubani (Mithila) painting received a GI tag in 2007; it was traditionally drawn by women on walls and floors.",
      "(D) Anga (Bhagalpur region) is known for Manjusha art; (A) Magadh and (C) Bhojpur are not the home of Madhubani painting."),
    solHi: p("<b>सही उत्तर: (B) मिथिला।</b> मधुबनी (मिथिला) चित्रकला को 2007 में GI टैग मिला; परंपरागत रूप से महिलाएँ इसे दीवारों व फ़र्श पर बनाती थीं।",
      "(D) अंग (भागलपुर क्षेत्र) मंजूषा कला के लिए प्रसिद्ध है; (A) मगध और (C) भोजपुर मधुबनी चित्रकला के मूल क्षेत्र नहीं हैं।"),
  },
  {
    s: "geography", t: "bihar", exam: "63rd", d: "easy", theme: "kosi", hp: true,
    en: "Which river is known as the 'Sorrow of Bihar'?",
    hi: "किस नदी को 'बिहार का शोक' कहा जाता है?",
    options: O(["Gandak", "गंडक"], ["Kosi", "कोसी"], ["Son", "सोन"], ["Bagmati", "बागमती"]),
    ans: "B",
    solEn: p("<b>Correct: (B) Kosi.</b> It carries a very high silt load from the Himalayas and has shifted its course westward by more than 100 km over two centuries, causing frequent floods (e.g. Kusaha breach, 2008).",
      "(A) Gandak and (D) Bagmati also flood, but the title belongs to the Kosi. (C) Son is a south-bank peninsular river."),
    solHi: p("<b>सही उत्तर: (B) कोसी।</b> यह हिमालय से भारी मात्रा में गाद लाती है और पिछले दो सौ वर्षों में 100 किमी से अधिक पश्चिम की ओर मार्ग बदल चुकी है, जिससे बार-बार बाढ़ आती है (जैसे कुसहा तटबंध टूटना, 2008)।",
      "(A) गंडक और (D) बागमती में भी बाढ़ आती है, पर यह उपाधि कोसी की है। (C) सोन गंगा के दक्षिण से आने वाली प्रायद्वीपीय नदी है।"),
  },
  {
    s: "geography", t: "bihar", exam: "69th", d: "medium", theme: "kosi",
    en: "The Kosi river enters Bihar from which country?",
    hi: "कोसी नदी किस देश से होकर बिहार में प्रवेश करती है?",
    options: O(["Bhutan", "भूटान"], ["Nepal", "नेपाल"], ["Bangladesh", "बांग्लादेश"], ["China (Tibet) directly", "सीधे चीन (तिब्बत) से"], MORE_THAN_ONE),
    ans: "B",
    solEn: p("<b>Correct: (B) Nepal.</b> The Kosi (Sapta Kosi) is formed in Nepal by seven Himalayan streams (its headwaters such as the Arun rise in Tibet) and enters Bihar near Bhimnagar (Supaul district), close to the Kosi barrage on the India–Nepal border.",
      "It does not flow through Bhutan or Bangladesh, and it does not enter Bihar directly from Tibet — so (A), (C), (D) and (E) are wrong."),
    solHi: p("<b>सही उत्तर: (B) नेपाल।</b> कोसी (सप्तकोसी) नेपाल में सात हिमालयी धाराओं से बनती है (अरुण जैसी उपधाराएँ तिब्बत से निकलती हैं) और भारत–नेपाल सीमा पर स्थित कोसी बराज के निकट भीमनगर (सुपौल ज़िला) के पास बिहार में प्रवेश करती है।",
      "यह भूटान या बांग्लादेश से नहीं बहती और न ही सीधे तिब्बत से बिहार में आती है — अतः (A), (C), (D), (E) गलत हैं।"),
  },
  {
    s: "geography", t: "physical", exam: "65th", d: "easy",
    en: "The ozone layer is found mainly in which layer of the atmosphere?",
    hi: "ओज़ोन परत मुख्य रूप से वायुमंडल की किस परत में पाई जाती है?",
    options: O(["Troposphere", "क्षोभमंडल"], ["Stratosphere", "समतापमंडल"], ["Mesosphere", "मध्यमंडल"], ["Thermosphere", "तापमंडल"]),
    ans: "B",
    solEn: p("<b>Correct: (B) Stratosphere</b> — roughly 15–35 km above the surface; the ozone absorbs harmful UV-B radiation.",
      "(A) The troposphere is where weather occurs. (C) Meteors burn up in the mesosphere. (D) The thermosphere contains the ionosphere, which reflects radio waves."),
    solHi: p("<b>सही उत्तर: (B) समतापमंडल</b> — सतह से लगभग 15–35 किमी ऊपर; ओज़ोन हानिकारक UV-B विकिरण को अवशोषित करती है।",
      "(A) क्षोभमंडल में मौसम संबंधी घटनाएँ होती हैं। (C) उल्काएँ मध्यमंडल में जलती हैं। (D) तापमंडल में आयनमंडल है, जो रेडियो तरंगों को परावर्तित करता है।"),
  },
  {
    s: "geography", t: "world", exam: "67th", d: "medium",
    en: "The Strait of Malacca separates:",
    hi: "मलक्का जलडमरूमध्य किन्हें अलग करता है?",
    options: O(["India and Sri Lanka", "भारत और श्रीलंका"], ["Malay Peninsula and Sumatra", "मलय प्रायद्वीप और सुमात्रा"], ["Java and Sumatra", "जावा और सुमात्रा"], ["Africa and Europe", "अफ़्रीका और यूरोप"], NONE),
    ans: "B",
    solEn: p("<b>Correct: (B)</b> The Strait of Malacca lies between the Malay Peninsula and the Indonesian island of Sumatra — one of the busiest shipping lanes linking the Indian and Pacific Oceans.",
      "(A) India–Sri Lanka: Palk Strait. (C) Java–Sumatra: Sunda Strait. (D) Africa–Europe: Strait of Gibraltar."),
    solHi: p("<b>सही उत्तर: (B)</b> मलक्का जलडमरूमध्य मलय प्रायद्वीप और इंडोनेशिया के सुमात्रा द्वीप के बीच है — हिंद और प्रशांत महासागर को जोड़ने वाला व्यस्ततम समुद्री मार्ग।",
      "(A) भारत–श्रीलंका: पाक जलडमरूमध्य। (C) जावा–सुमात्रा: सुंडा जलडमरूमध्य। (D) अफ़्रीका–यूरोप: जिब्राल्टर जलडमरूमध्य।"),
  },
  {
    s: "polity", t: "fundamental-rights", exam: "67th", d: "easy", theme: "fundamental-rights",
    en: "Which Article of the Indian Constitution abolishes untouchability?",
    hi: "भारतीय संविधान का कौन-सा अनुच्छेद अस्पृश्यता का उन्मूलन करता है?",
    options: O(["Article 14", "अनुच्छेद 14"], ["Article 15", "अनुच्छेद 15"], ["Article 17", "अनुच्छेद 17"], ["Article 21", "अनुच्छेद 21"], MORE_THAN_ONE),
    ans: "C",
    solEn: p("<b>Correct: (C) Article 17</b> abolishes untouchability and forbids its practice in any form; it is enforced through the Protection of Civil Rights Act, 1955.",
      "(A) Art 14 — equality before law. (B) Art 15 — no discrimination on grounds of religion, race, caste, sex or place of birth. (D) Art 21 — life and personal liberty. Only one article is correct, so (E) is wrong."),
    solHi: p("<b>सही उत्तर: (C) अनुच्छेद 17</b> अस्पृश्यता का अंत करता है और किसी भी रूप में इसके आचरण को निषिद्ध करता है; इसे नागरिक अधिकार संरक्षण अधिनियम, 1955 द्वारा लागू किया जाता है।",
      "(A) अनु. 14 — विधि के समक्ष समता। (B) अनु. 15 — धर्म, मूलवंश, जाति, लिंग या जन्मस्थान के आधार पर भेदभाव का निषेध। (D) अनु. 21 — प्राण एवं दैहिक स्वतंत्रता। केवल एक अनुच्छेद सही है, अतः (E) गलत है।"),
  },
  {
    s: "polity", t: "constitution", exam: "64th", d: "easy", theme: "preamble",
    en: "The words 'Socialist' and 'Secular' were added to the Preamble by which Constitutional Amendment?",
    hi: "'समाजवादी' और 'पंथनिरपेक्ष' शब्द प्रस्तावना में किस संविधान संशोधन द्वारा जोड़े गए?",
    options: O(["42nd Amendment", "42वाँ संशोधन"], ["44th Amendment", "44वाँ संशोधन"], ["24th Amendment", "24वाँ संशोधन"], ["52nd Amendment", "52वाँ संशोधन"]),
    ans: "A",
    solEn: p("<b>Correct: (A) 42nd Amendment Act, 1976</b> added 'Socialist', 'Secular' and 'Integrity'. It is the only amendment to the Preamble so far.",
      "(B) 44th (1978) removed the right to property from Fundamental Rights. (C) 24th (1971) affirmed Parliament's power to amend Fundamental Rights. (D) 52nd (1985) added the Anti-Defection law (Tenth Schedule)."),
    solHi: p("<b>सही उत्तर: (A) 42वाँ संशोधन अधिनियम, 1976</b> — इसने 'समाजवादी', 'पंथनिरपेक्ष' और 'अखंडता' शब्द जोड़े। प्रस्तावना में अब तक यही एकमात्र संशोधन है।",
      "(B) 44वें (1978) ने संपत्ति के अधिकार को मौलिक अधिकारों से हटाया। (C) 24वें (1971) ने मौलिक अधिकारों में संशोधन की संसद की शक्ति की पुष्टि की। (D) 52वें (1985) ने दल-बदल विरोधी कानून (दसवीं अनुसूची) जोड़ा।"),
  },
  {
    s: "polity", t: "local-government", exam: "69th", d: "medium", theme: "panchayati-raj",
    en: "<p>Consider the following statements:</p><ol><li>The 73rd Constitutional Amendment Act added Part IX to the Constitution.</li><li>Bihar was the first state to provide 50% reservation for women in Panchayati Raj Institutions.</li></ol><p>Which of the statements given above is/are correct?</p>",
    hi: "<p>निम्नलिखित कथनों पर विचार कीजिए:</p><ol><li>73वें संविधान संशोधन अधिनियम ने संविधान में भाग IX जोड़ा।</li><li>पंचायती राज संस्थाओं में महिलाओं को 50% आरक्षण देने वाला बिहार पहला राज्य था।</li></ol><p>उपर्युक्त में से कौन-सा/से कथन सही है/हैं?</p>",
    options: O(["1 only", "केवल 1"], ["2 only", "केवल 2"], ["Both 1 and 2", "1 और 2 दोनों"], ["Neither 1 nor 2", "न तो 1 और न ही 2"]),
    ans: "C",
    solEn: p("<b>Correct: (C) Both.</b> Statement 1: the 73rd Amendment (1992) added Part IX ('The Panchayats', Art 243–243O) and the Eleventh Schedule. Statement 2: Bihar's Panchayat Raj Act, 2006 made it the first state to reserve 50% of panchayat seats for women."),
    solHi: p("<b>सही उत्तर: (C) दोनों।</b> कथन 1: 73वें संशोधन (1992) ने भाग IX ('पंचायतें', अनु. 243–243O) तथा ग्यारहवीं अनुसूची जोड़ी। कथन 2: बिहार पंचायत राज अधिनियम, 2006 के ज़रिए बिहार पंचायतों में महिलाओं को 50% आरक्षण देने वाला पहला राज्य बना।"),
  },
  {
    s: "bihar-special", t: "bihar-polity", exam: "66th", d: "medium",
    en: "In which year was the Patna High Court established?",
    hi: "पटना उच्च न्यायालय की स्थापना किस वर्ष हुई?",
    options: O(["1912", "1912"], ["1916", "1916"], ["1936", "1936"], ["1950", "1950"]),
    ans: "B",
    solEn: p("<b>Correct: (B) 1916.</b> The Patna High Court was inaugurated by Viceroy Lord Hardinge on 3 February 1916, four years after Bihar & Orissa were separated from Bengal.",
      "(A) 1912 — Bihar & Orissa province created. (C) 1936 — Orissa became a separate province. (D) 1950 — the Constitution came into force."),
    solHi: p("<b>सही उत्तर: (B) 1916.</b> पटना उच्च न्यायालय का उद्घाटन वायसराय लॉर्ड हार्डिंग ने 3 फ़रवरी 1916 को किया, बंगाल से बिहार–उड़ीसा के अलग होने के चार वर्ष बाद।",
      "(A) 1912 — बिहार व उड़ीसा प्रांत बना। (C) 1936 — उड़ीसा अलग प्रांत बना। (D) 1950 — संविधान लागू हुआ।"),
  },
  {
    s: "economy", t: "banking", exam: "68th", d: "easy", theme: "monetary-policy",
    en: "The 'Repo Rate' is the rate at which:",
    hi: "'रेपो दर' वह दर है जिस पर:",
    options: O(["Commercial banks park surplus funds with the RBI", "वाणिज्यिक बैंक अपनी अतिरिक्त राशि RBI के पास रखते हैं"], ["The RBI lends short-term funds to commercial banks against government securities", "RBI सरकारी प्रतिभूतियों के बदले वाणिज्यिक बैंकों को अल्पकालिक ऋण देता है"], ["Commercial banks lend to their best customers", "वाणिज्यिक बैंक अपने सर्वोत्तम ग्राहकों को ऋण देते हैं"], ["The government borrows from the public", "सरकार जनता से उधार लेती है"]),
    ans: "B",
    solEn: p("<b>Correct: (B).</b> Under repo (repurchase agreement) the RBI lends to banks against securities, which banks repurchase later. A higher repo makes borrowing costlier and is used to curb inflation.",
      "(A) describes the reverse repo / Standing Deposit Facility. (C) describes a bank's lending rate (MCLR/prime rate). (D) describes government borrowing through bonds."),
    solHi: p("<b>सही उत्तर: (B)।</b> रेपो (पुनर्खरीद समझौता) के अंतर्गत RBI प्रतिभूतियों के बदले बैंकों को ऋण देता है, जिन्हें बैंक बाद में पुनः खरीदते हैं। रेपो बढ़ने से उधार महँगा होता है — यह मुद्रास्फीति नियंत्रण का उपाय है।",
      "(A) रिवर्स रेपो / स्थायी जमा सुविधा (SDF) है। (C) बैंक की ऋण दर (MCLR/प्राइम रेट) है। (D) बॉन्ड के ज़रिए सरकारी उधारी है।"),
  },
  {
    s: "economy", t: "national-income", exam: "65th", d: "medium",
    en: "GDP at market price minus depreciation is equal to:",
    hi: "बाज़ार मूल्य पर GDP में से मूल्यह्रास घटाने पर क्या प्राप्त होता है?",
    options: O(["GNP at market price", "बाज़ार मूल्य पर GNP"], ["NDP at market price", "बाज़ार मूल्य पर NDP"], ["NNP at factor cost", "साधन लागत पर NNP"], ["GDP at factor cost", "साधन लागत पर GDP"]),
    ans: "B",
    solEn: p("<b>Correct: (B) NDP<sub>MP</sub> = GDP<sub>MP</sub> − Depreciation.</b>",
      "(A) GNP = GDP + Net Factor Income from Abroad. (C) NNP<sub>FC</sub> = NNP<sub>MP</sub> − Net Indirect Taxes (national income). (D) GDP<sub>FC</sub> = GDP<sub>MP</sub> − Net Indirect Taxes."),
    solHi: p("<b>सही उत्तर: (B) NDP<sub>MP</sub> = GDP<sub>MP</sub> − मूल्यह्रास।</b>",
      "(A) GNP = GDP + विदेश से शुद्ध साधन आय। (C) NNP<sub>FC</sub> = NNP<sub>MP</sub> − शुद्ध अप्रत्यक्ष कर (राष्ट्रीय आय)। (D) GDP<sub>FC</sub> = GDP<sub>MP</sub> − शुद्ध अप्रत्यक्ष कर।"),
  },
  {
    s: "economy", t: "fiscal-policy", exam: "70th", d: "medium", theme: "deficits", hp: true,
    en: "Fiscal deficit is defined as:",
    hi: "राजकोषीय घाटे की परिभाषा है:",
    options: O(["Revenue expenditure − Revenue receipts", "राजस्व व्यय − राजस्व प्राप्तियाँ"], ["Total expenditure − Total receipts excluding borrowings", "कुल व्यय − उधार को छोड़कर कुल प्राप्तियाँ"], ["Fiscal deficit − Interest payments", "राजकोषीय घाटा − ब्याज भुगतान"], ["Total expenditure − Revenue receipts", "कुल व्यय − राजस्व प्राप्तियाँ"], MORE_THAN_ONE),
    ans: "B",
    solEn: p("<b>Correct: (B).</b> Fiscal deficit = Total expenditure − (Revenue receipts + non-debt capital receipts); it equals the government's total borrowing requirement.",
      "(A) is Revenue deficit. (C) is Primary deficit. (D) ignores non-debt capital receipts (e.g. disinvestment, loan recoveries), so it is not the fiscal deficit."),
    solHi: p("<b>सही उत्तर: (B)।</b> राजकोषीय घाटा = कुल व्यय − (राजस्व प्राप्तियाँ + गैर-ऋण पूँजीगत प्राप्तियाँ); यह सरकार की कुल उधारी आवश्यकता के बराबर है।",
      "(A) राजस्व घाटा है। (C) प्राथमिक घाटा है। (D) में गैर-ऋण पूँजीगत प्राप्तियाँ (जैसे विनिवेश, ऋण वसूली) छूट जाती हैं, इसलिए यह राजकोषीय घाटा नहीं है।"),
  },
  {
    s: "economy", t: "bihar-economy", exam: "67th", d: "easy", theme: "gi-tags",
    en: "'Shahi Litchi', which received a GI tag, is associated with which district of Bihar?",
    hi: "GI टैग प्राप्त 'शाही लीची' बिहार के किस ज़िले से संबंधित है?",
    options: O(["Muzaffarpur", "मुज़फ़्फ़रपुर"], ["Bhagalpur", "भागलपुर"], ["Gaya", "गया"], ["Darbhanga", "दरभंगा"], NONE),
    ans: "A",
    solEn: p("<b>Correct: (A) Muzaffarpur.</b> Shahi Litchi of Muzaffarpur got its GI tag in 2018.",
      "(B) Bhagalpur is known for Jardalu mango and Bhagalpuri silk. (C) Gaya is known for Tilkut. (D) Darbhanga is famous for Makhana, which is marketed as 'Mithila Makhana' (GI 2022)."),
    solHi: p("<b>सही उत्तर: (A) मुज़फ़्फ़रपुर।</b> मुज़फ़्फ़रपुर की शाही लीची को 2018 में GI टैग मिला।",
      "(B) भागलपुर जर्दालु आम व भागलपुरी सिल्क के लिए प्रसिद्ध है। (C) गया तिलकुट के लिए। (D) दरभंगा मखाना के लिए प्रसिद्ध है, जिसे 'मिथिला मखाना' (GI 2022) कहा जाता है।"),
  },
  {
    s: "science", t: "chemistry", exam: "63rd", d: "easy",
    en: "What is the chemical formula of baking soda?",
    hi: "खाने के सोडा (बेकिंग सोडा) का रासायनिक सूत्र क्या है?",
    options: O(["Na<sub>2</sub>CO<sub>3</sub>", "Na<sub>2</sub>CO<sub>3</sub>"], ["NaHCO<sub>3</sub>", "NaHCO<sub>3</sub>"], ["NaOH", "NaOH"], ["CaCO<sub>3</sub>", "CaCO<sub>3</sub>"]),
    ans: "B",
    solEn: p("<b>Correct: (B) NaHCO<sub>3</sub></b> — sodium hydrogen carbonate (sodium bicarbonate). On heating it releases CO<sub>2</sub>, which makes dough rise.",
      "(A) Na<sub>2</sub>CO<sub>3</sub> is washing soda (as decahydrate). (C) NaOH is caustic soda. (D) CaCO<sub>3</sub> is limestone/chalk/marble."),
    solHi: p("<b>सही उत्तर: (B) NaHCO<sub>3</sub></b> — सोडियम हाइड्रोजन कार्बोनेट (सोडियम बाइकार्बोनेट)। गर्म करने पर यह CO<sub>2</sub> छोड़ता है, जिससे आटा फूलता है।",
      "(A) Na<sub>2</sub>CO<sub>3</sub> धोने का सोडा (डेकाहाइड्रेट रूप में) है। (C) NaOH कास्टिक सोडा है। (D) CaCO<sub>3</sub> चूना-पत्थर/खड़िया/संगमरमर है।"),
  },
  {
    s: "science", t: "biology", exam: "69th", d: "easy", theme: "vitamins",
    en: "Deficiency of Vitamin C causes:",
    hi: "विटामिन C की कमी से कौन-सा रोग होता है?",
    options: O(["Rickets", "रिकेट्स (सूखा रोग)"], ["Scurvy", "स्कर्वी"], ["Beriberi", "बेरीबेरी"], ["Night blindness", "रतौंधी"], MORE_THAN_ONE),
    ans: "B",
    solEn: p("<b>Correct: (B) Scurvy</b> — bleeding gums and poor wound healing, because vitamin C (ascorbic acid) is needed for collagen synthesis.",
      "(A) Rickets — vitamin D. (C) Beriberi — vitamin B1 (thiamine). (D) Night blindness — vitamin A. Only one disease matches, so (E) is wrong."),
    solHi: p("<b>सही उत्तर: (B) स्कर्वी</b> — मसूड़ों से रक्तस्राव और घाव देर से भरना, क्योंकि कोलेजन निर्माण के लिए विटामिन C (एस्कॉर्बिक अम्ल) आवश्यक है।",
      "(A) रिकेट्स — विटामिन D। (C) बेरीबेरी — विटामिन B1 (थायमिन)। (D) रतौंधी — विटामिन A। केवल एक रोग मेल खाता है, अतः (E) गलत है।"),
  },
  {
    s: "science", t: "biology", exam: "64th", d: "easy", theme: "blood-groups",
    en: "People with which blood group are called 'universal donors'?",
    hi: "किस रक्त समूह वाले व्यक्तियों को 'सर्वदाता' कहा जाता है?",
    options: O(["A", "A"], ["B", "B"], ["AB", "AB"], ["O", "O"]),
    ans: "D",
    solEn: p("<b>Correct: (D) O</b> (specifically O-negative) — its red cells carry no A or B antigens, so they are not attacked by anti-A/anti-B antibodies in the recipient.",
      "(C) AB is the universal recipient because its plasma has no anti-A or anti-B antibodies. (A) and (B) can donate only to matching/AB groups."),
    solHi: p("<b>सही उत्तर: (D) O</b> (विशेषकर O-नेगेटिव) — इसकी लाल रक्त कोशिकाओं पर A या B प्रतिजन नहीं होते, अतः प्राप्तकर्ता के एंटी-A/एंटी-B प्रतिरक्षी उन पर आक्रमण नहीं करते।",
      "(C) AB सर्वग्राही है, क्योंकि इसके प्लाज़्मा में एंटी-A या एंटी-B प्रतिरक्षी नहीं होते। (A) व (B) केवल समान/AB समूह को रक्त दे सकते हैं।"),
  },
  {
    s: "current-affairs", t: "international", exam: "69th", d: "easy", theme: "g20",
    en: "The G20 Leaders' Summit held under India's presidency in September 2023 took place in:",
    hi: "भारत की अध्यक्षता में सितंबर 2023 में आयोजित G20 शिखर सम्मेलन कहाँ हुआ?",
    options: O(["Mumbai", "मुंबई"], ["New Delhi", "नई दिल्ली"], ["Bengaluru", "बेंगलुरु"], ["Hyderabad", "हैदराबाद"], NONE),
    ans: "B",
    solEn: p("<b>Correct: (B) New Delhi</b>, at the Bharat Mandapam (9–10 September 2023). The African Union was admitted as a permanent member at this summit; the theme was 'Vasudhaiva Kutumbakam — One Earth, One Family, One Future'.",
      "Mumbai, Bengaluru and Hyderabad hosted ministerial/working-group meetings during the presidency, not the leaders' summit."),
    solHi: p("<b>सही उत्तर: (B) नई दिल्ली</b>, भारत मंडपम में (9–10 सितंबर 2023)। इसी सम्मेलन में अफ़्रीकी संघ को स्थायी सदस्य बनाया गया; थीम थी 'वसुधैव कुटुम्बकम् — एक पृथ्वी, एक परिवार, एक भविष्य'।",
      "मुंबई, बेंगलुरु और हैदराबाद में अध्यक्षता के दौरान मंत्रिस्तरीय/कार्य-समूह बैठकें हुईं, शिखर सम्मेलन नहीं।"),
  },
  {
    s: "current-affairs", t: "science-tech", exam: "70th", d: "medium", theme: "chandrayaan",
    en: "India observes 'National Space Day' on which date, marking the Chandrayaan-3 landing?",
    hi: "चंद्रयान-3 की लैंडिंग की स्मृति में भारत 'राष्ट्रीय अंतरिक्ष दिवस' किस तिथि को मनाता है?",
    options: O(["23 August", "23 अगस्त"], ["15 August", "15 अगस्त"], ["14 July", "14 जुलाई"], ["28 February", "28 फ़रवरी"]),
    ans: "A",
    solEn: p("<b>Correct: (A) 23 August.</b> Chandrayaan-3's Vikram lander touched down near the lunar south pole on 23 August 2023; the landing site was named 'Shiv Shakti Point'.",
      "(C) 14 July 2023 was Chandrayaan-3's launch date. (D) 28 February is National Science Day (Raman Effect). (B) is Independence Day."),
    solHi: p("<b>सही उत्तर: (A) 23 अगस्त।</b> चंद्रयान-3 का विक्रम लैंडर 23 अगस्त 2023 को चंद्रमा के दक्षिणी ध्रुव के पास उतरा; लैंडिंग स्थल का नाम 'शिव शक्ति पॉइंट' रखा गया।",
      "(C) 14 जुलाई 2023 चंद्रयान-3 के प्रक्षेपण की तिथि थी। (D) 28 फ़रवरी राष्ट्रीय विज्ञान दिवस (रमन प्रभाव) है। (B) स्वतंत्रता दिवस है।"),
  },
  {
    s: "bihar-special", t: "bihar-culture", exam: "65th", d: "easy", theme: "bihar-diwas",
    en: "Bihar Diwas (Bihar Day) is celebrated every year on:",
    hi: "बिहार दिवस प्रतिवर्ष किस तिथि को मनाया जाता है?",
    options: O(["22 March", "22 मार्च"], ["26 January", "26 जनवरी"], ["15 November", "15 नवंबर"], ["1 April", "1 अप्रैल"]),
    ans: "A",
    solEn: p("<b>Correct: (A) 22 March</b> — on this day in 1912, Bihar (with Orissa) was carved out of the Bengal Presidency.",
      "(C) 15 November 2000 — Jharkhand was formed from Bihar. (D) 1 April 1936 — Orissa became a separate province. (B) is Republic Day."),
    solHi: p("<b>सही उत्तर: (A) 22 मार्च</b> — 1912 में इसी दिन बिहार (उड़ीसा सहित) को बंगाल प्रेसिडेंसी से अलग किया गया था।",
      "(C) 15 नवंबर 2000 — बिहार से झारखंड बना। (D) 1 अप्रैल 1936 — उड़ीसा अलग प्रांत बना। (B) गणतंत्र दिवस है।"),
  },
  {
    s: "bihar-special", t: "bihar-schemes", exam: "68th", d: "easy", theme: "saat-nischay",
    en: "'Har Ghar Nal Ka Jal' is a component of which Bihar government initiative?",
    hi: "'हर घर नल का जल' बिहार सरकार की किस पहल का घटक है?",
    options: O(["Saat Nischay", "सात निश्चय"], ["Jal-Jeevan-Hariyali", "जल-जीवन-हरियाली"], ["Mukhyamantri Kanya Utthan Yojana", "मुख्यमंत्री कन्या उत्थान योजना"], ["Kushal Yuva Program", "कुशल युवा कार्यक्रम"]),
    ans: "A",
    solEn: p("<b>Correct: (A) Saat Nischay</b> (Seven Resolves, 2015). Its components include Har Ghar Nal Ka Jal, Har Ghar Bijli, Ghar Tak Pakki Gali-Naliyan, Shauchalay Nirman, Aarakshit Rozgar Mahilaon ka Adhikar, Aarthik Hal Yuvaon ko Bal and Avsar Badhe Aage Padhe.",
      "(B) Jal-Jeevan-Hariyali (2019) is about water conservation and greenery. (C) is a girls' education/incentive scheme. (D) Kushal Yuva Program is itself part of 'Aarthik Hal, Yuvaon ko Bal' under Saat Nischay."),
    solHi: p("<b>सही उत्तर: (A) सात निश्चय</b> (2015)। इसके घटक हैं — हर घर नल का जल, हर घर बिजली, घर तक पक्की गली-नालियाँ, शौचालय निर्माण, आरक्षित रोज़गार महिलाओं का अधिकार, आर्थिक हल युवाओं को बल तथा अवसर बढ़े आगे पढ़ें।",
      "(B) जल-जीवन-हरियाली (2019) जल संरक्षण व हरियाली से संबंधित है। (C) बालिका शिक्षा/प्रोत्साहन योजना है। (D) कुशल युवा कार्यक्रम स्वयं सात निश्चय के 'आर्थिक हल, युवाओं को बल' का भाग है।"),
  },
  {
    s: "mental-ability", t: "number-series", exam: "67th", d: "easy",
    en: "Find the next number in the series: 2, 6, 12, 20, 30, ?",
    hi: "श्रृंखला में अगली संख्या ज्ञात कीजिए: 2, 6, 12, 20, 30, ?",
    options: O(["40", "40"], ["42", "42"], ["44", "44"], ["36", "36"], NONE),
    ans: "B",
    solEn: p("<b>Correct: (B) 42.</b> The terms are n(n+1): 1×2, 2×3, 3×4, 4×5, 5×6, so next = 6×7 = 42. Equivalently the differences are 4, 6, 8, 10 → next difference 12 → 30 + 12 = 42."),
    solHi: p("<b>सही उत्तर: (B) 42.</b> पद n(n+1) हैं: 1×2, 2×3, 3×4, 4×5, 5×6, अतः अगला = 6×7 = 42। अंतर 4, 6, 8, 10 हैं → अगला अंतर 12 → 30 + 12 = 42।"),
  },
  {
    s: "mental-ability", t: "arithmetic", exam: "68th", d: "medium",
    en: "A sum of money doubles itself in 8 years at simple interest. What is the rate of interest per annum?",
    hi: "कोई धनराशि साधारण ब्याज पर 8 वर्षों में दोगुनी हो जाती है। वार्षिक ब्याज दर क्या है?",
    options: O(["10%", "10%"], ["12.5%", "12.5%"], ["8%", "8%"], ["15%", "15%"], NONE),
    ans: "B",
    solEn: p("<b>Correct: (B) 12.5%.</b> Doubling means SI = P. So P = P × R × 8 / 100 → R = 100/8 = 12.5%."),
    solHi: p("<b>सही उत्तर: (B) 12.5%.</b> दोगुना होने का अर्थ है साधारण ब्याज = P। अतः P = P × R × 8 / 100 → R = 100/8 = 12.5%।"),
  },
  {
    s: "mental-ability", t: "coding-decoding", exam: "71st", d: "easy",
    en: "If in a certain code PATNA is written as QBUOB, how is GAYA written in that code?",
    hi: "यदि किसी कूट भाषा में PATNA को QBUOB लिखा जाता है, तो उसी कूट में GAYA को कैसे लिखा जाएगा?",
    options: O(["HBZB", "HBZB"], ["HBYB", "HBYB"], ["GBZB", "GBZB"], ["IBZC", "IBZC"], NONE),
    ans: "A",
    solEn: p("<b>Correct: (A) HBZB.</b> Each letter is shifted one place forward: P→Q, A→B, T→U, N→O, A→B. So G→H, A→B, Y→Z, A→B = HBZB."),
    solHi: p("<b>सही उत्तर: (A) HBZB.</b> प्रत्येक अक्षर को एक स्थान आगे बढ़ाया गया है: P→Q, A→B, T→U, N→O, A→B। अतः G→H, A→B, Y→Z, A→B = HBZB।"),
  },
  // Example of a question dropped by BPSC — stays in the DB but never appears in quizzes.
  {
    s: "geography", t: "bihar", exam: "66th", d: "medium", dropped: true,
    en: "Which is the longest river flowing within Bihar?",
    hi: "बिहार में बहने वाली सबसे लंबी नदी कौन-सी है?",
    options: O(["Ganga", "गंगा"], ["Ghaghara", "घाघरा"], ["Gandak", "गंडक"], ["Kosi", "कोसी"]),
    ans: "A",
    solEn: p("<i>Sample dropped question:</i> ambiguous wording (total length vs. length within the state) — the kind of question BPSC cancels. It is kept for record but excluded from all quizzes."),
    solHi: p("<i>नमूना निरस्त प्रश्न:</i> अस्पष्ट शब्दावली (कुल लंबाई बनाम राज्य के भीतर लंबाई) — ऐसे प्रश्न BPSC रद्द करता है। यह रिकॉर्ड में है पर किसी क्विज़ में नहीं आता।"),
  },
];
