-- =====================================================================
-- GS Hub BPSC PYQ Portal — core schema
-- Run in Supabase SQL editor (or `supabase db push`). Idempotent-ish:
-- intended for a fresh project.
-- =====================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- Profiles & roles
-- ---------------------------------------------------------------------
create table public.profiles (
  id             text primary key,
  full_name      text,
  phone          text,
  role           text not null default 'student' check (role in ('student','admin')),
  preferred_lang text not null default 'en' check (preferred_lang in ('en','hi')),
  created_at     timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.phone
  )
  on conflict (id) do nothing;
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = (auth.jwt()->>'sub') and role = 'admin');
$$;

-- ---------------------------------------------------------------------
-- Taxonomy: exams, subjects, topics
-- ---------------------------------------------------------------------
create table public.exams (
  id          int generated by default as identity primary key,
  short_name  text not null unique,                 -- e.g. '70th'
  name_en     text not null,                        -- '70th BPSC Integrated Prelims'
  name_hi     text,
  year        int,                                  -- calendar year of the exam
  category    text not null default 'pyq'
              check (category in ('pyq','current_affairs','test_series','other')),
  sort_order  int not null default 0,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

create table public.subjects (
  id          int generated by default as identity primary key,
  slug        text not null unique,
  name_en     text not null,
  name_hi     text not null,
  icon        text,
  sort_order  int not null default 0
);

create table public.topics (
  id          int generated by default as identity primary key,
  subject_id  int not null references public.subjects(id) on delete cascade,
  slug        text not null,
  name_en     text not null,
  name_hi     text not null,
  sort_order  int not null default 0,
  unique (subject_id, slug)
);
create index on public.topics (subject_id);

-- ---------------------------------------------------------------------
-- Questions
-- options: [{"key":"A","en":"...","hi":"..."}, ...]  (2–5 items, A–E)
-- question/solution fields hold sanitised HTML (tables, images allowed)
-- ---------------------------------------------------------------------
create table public.questions (
  id               uuid primary key default gen_random_uuid(),
  exam_id          int references public.exams(id) on delete set null,
  year             int,
  subject_id       int not null references public.subjects(id) on delete restrict,
  topic_id         int references public.topics(id) on delete set null,
  difficulty       text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  question_en      text not null,
  question_hi      text,
  options          jsonb not null
                   check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) between 2 and 5),
  correct_option   text not null check (correct_option in ('A','B','C','D','E')),
  solution_en      text,
  solution_hi      text,
  is_dropped       boolean not null default false,   -- dropped/cancelled by BPSC
  is_high_priority boolean not null default false,   -- manual flag by staff
  theme            text,                             -- repeated-theme tag, e.g. 'champaran'
  source           text not null default 'pyq',      -- 'pyq' | 'sample' | 'current_affairs' | 'test_series'
  created_by       uuid references auth.users(id) on delete set null default (auth.jwt()->>'sub'),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index on public.questions (subject_id, topic_id) where not is_dropped;
create index on public.questions (exam_id);
create index on public.questions (theme);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

create trigger questions_touch before update on public.questions
  for each row execute function public.touch_updated_at();

-- Computed column (PostgREST exposes it as `high_priority` on questions):
-- a question is high priority when staff flagged it, OR its theme has been
-- asked in 2+ different exams/years (a repeated theme).
create or replace function public.high_priority(q public.questions)
returns boolean language sql stable as $$
  select q.is_high_priority
      or (q.theme is not null and (
            select count(distinct coalesce(q2.exam_id::text, q2.year::text, q2.id::text))
            from public.questions q2
            where q2.theme = q.theme and not q2.is_dropped
          ) >= 2);
$$;

-- ---------------------------------------------------------------------
-- App settings (single row): marking scheme etc.
-- ---------------------------------------------------------------------
create table public.app_settings (
  id                   int primary key default 1 check (id = 1),
  positive_marks       numeric(5,2) not null default 1,
  negative_marks       numeric(5,2) not null default 0.33,
  seconds_per_question int not null default 48,       -- 150 Q in 2 h = 48 s each
  min_stats_attempts   int not null default 5,        -- min users before showing "% solved"
  updated_at           timestamptz not null default now()
);
insert into public.app_settings (id) values (1) on conflict do nothing;

-- ---------------------------------------------------------------------
-- Quiz attempts
-- responses: {"<question_id>": {"selected":"B","review":false}, ...}
-- ---------------------------------------------------------------------
create table public.quiz_attempts (
  id              uuid primary key default gen_random_uuid(),
  user_id         text not null default (auth.jwt()->>'sub'),
  title           text,
  mode            text not null check (mode in ('practice','exam')),
  source          text not null default 'all' check (source in ('all','bookmarks','mistakes')),
  config          jsonb not null default '{}'::jsonb,
  question_ids    uuid[] not null,
  responses       jsonb not null default '{}'::jsonb,
  current_index   int not null default 0,
  positive_marks  numeric(5,2),
  negative_marks  numeric(5,2),
  time_limit_sec  int,
  status          text not null default 'in_progress' check (status in ('in_progress','submitted')),
  started_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  submitted_at    timestamptz,
  time_taken_sec  int,
  score           numeric(7,2),
  correct_count   int,
  wrong_count     int,
  skipped_count   int,
  total_count     int
);
create index on public.quiz_attempts (user_id, started_at desc);

-- Marking is always taken from app_settings; clients cannot choose their own.
create or replace function public.quiz_attempts_before_insert()
returns trigger language plpgsql security definer set search_path = public as $$
declare s public.app_settings;
begin
  select * into s from public.app_settings where id = 1;
  new.user_id        := (auth.jwt()->>'sub');
  new.positive_marks := s.positive_marks;
  new.negative_marks := s.negative_marks;
  new.time_limit_sec := case when new.mode = 'exam'
                             then cardinality(new.question_ids) * s.seconds_per_question end;
  new.status := 'in_progress';
  new.score := null; new.correct_count := null; new.wrong_count := null;
  new.skipped_count := null; new.submitted_at := null;
  new.total_count := cardinality(new.question_ids);
  if cardinality(new.question_ids) < 1 or cardinality(new.question_ids) > 150 then
    raise exception 'A quiz must have between 1 and 150 questions';
  end if;
  return new;
end $$;

create trigger quiz_attempts_bi before insert on public.quiz_attempts
  for each row execute function public.quiz_attempts_before_insert();

create trigger quiz_attempts_touch before update on public.quiz_attempts
  for each row execute function public.touch_updated_at();

create table public.attempt_answers (
  id              bigint generated always as identity primary key,
  attempt_id      uuid not null references public.quiz_attempts(id) on delete cascade,
  user_id         text not null,
  question_id     uuid not null references public.questions(id) on delete cascade,
  selected_option text not null,
  is_correct      boolean not null,
  notebook_effect text check (notebook_effect in ('added','missed_again','cleared')),
  answered_at     timestamptz not null default now(),
  unique (attempt_id, question_id)
);
create index on public.attempt_answers (question_id);
create index on public.attempt_answers (user_id, answered_at);

-- ---------------------------------------------------------------------
-- Bookmarks & Mistake Notebook
-- ---------------------------------------------------------------------
create table public.bookmarks (
  user_id     text not null default (auth.jwt()->>'sub'),
  question_id uuid not null references public.questions(id) on delete cascade,
  note        text check (char_length(note) <= 500),
  created_at  timestamptz not null default now(),
  primary key (user_id, question_id)
);

create table public.mistakes (
  user_id         text not null,
  question_id     uuid not null references public.questions(id) on delete cascade,
  last_selected   text,
  times_missed    int not null default 1,
  first_missed_at timestamptz not null default now(),
  last_missed_at  timestamptz not null default now(),
  primary key (user_id, question_id)
);

-- ---------------------------------------------------------------------
-- Feedback / feature requests
-- ---------------------------------------------------------------------
create table public.feedback (
  id         bigint generated always as identity primary key,
  user_id    text default (auth.jwt()->>'sub'),
  kind       text not null default 'feedback' check (kind in ('feedback','feature','bug')),
  page       text,
  message    text not null check (char_length(message) between 3 and 2000),
  contact    text check (char_length(contact) <= 120),
  created_at timestamptz not null default now()
);

-- =====================================================================
-- Row-level security
-- =====================================================================
alter table public.profiles        enable row level security;
alter table public.exams           enable row level security;
alter table public.subjects        enable row level security;
alter table public.topics          enable row level security;
alter table public.questions       enable row level security;
alter table public.app_settings    enable row level security;
alter table public.quiz_attempts   enable row level security;
alter table public.attempt_answers enable row level security;
alter table public.bookmarks       enable row level security;
alter table public.mistakes        enable row level security;
alter table public.feedback        enable row level security;

-- profiles: own row (admins can read all). Role column can't be self-edited.
create policy "profiles: read own"   on public.profiles for select using (id = (auth.jwt()->>'sub') or public.is_admin());
create policy "profiles: update own" on public.profiles for update using (id = (auth.jwt()->>'sub')) with check (id = (auth.jwt()->>'sub'));
revoke update on public.profiles from anon, authenticated;
grant update (full_name, phone, preferred_lang) on public.profiles to authenticated;

-- taxonomy & settings: public read, admin write
create policy "exams: public read"    on public.exams    for select using (true);
create policy "exams: admin write"    on public.exams    for all using (public.is_admin()) with check (public.is_admin());
create policy "subjects: public read" on public.subjects for select using (true);
create policy "subjects: admin write" on public.subjects for all using (public.is_admin()) with check (public.is_admin());
create policy "topics: public read"   on public.topics   for select using (true);
create policy "topics: admin write"   on public.topics   for all using (public.is_admin()) with check (public.is_admin());
create policy "settings: public read" on public.app_settings for select using (true);
create policy "settings: admin write" on public.app_settings for update using (public.is_admin()) with check (public.is_admin());

-- questions: anyone can read live questions; admins see/edit everything
create policy "questions: read live" on public.questions for select using (not is_dropped or public.is_admin());
create policy "questions: admin write" on public.questions for all using (public.is_admin()) with check (public.is_admin());

-- quiz attempts: own rows only; scored fields are written only by submit_attempt()
create policy "attempts: read own"   on public.quiz_attempts for select using (user_id = (auth.jwt()->>'sub'));
create policy "attempts: insert own" on public.quiz_attempts for insert with check ((auth.jwt()->>'sub') is not null);
create policy "attempts: update own in-progress" on public.quiz_attempts for update
  using (user_id = (auth.jwt()->>'sub') and status = 'in_progress')
  with check (user_id = (auth.jwt()->>'sub') and status = 'in_progress');
create policy "attempts: delete own" on public.quiz_attempts for delete using (user_id = (auth.jwt()->>'sub'));
revoke update on public.quiz_attempts from anon, authenticated;
grant update (responses, current_index, title) on public.quiz_attempts to authenticated;

-- answers & mistakes: read own; writes only through security-definer RPCs
create policy "answers: read own"  on public.attempt_answers for select using (user_id = (auth.jwt()->>'sub'));
create policy "mistakes: read own" on public.mistakes for select using (user_id = (auth.jwt()->>'sub'));
create policy "mistakes: delete own" on public.mistakes for delete using (user_id = (auth.jwt()->>'sub'));

-- bookmarks: full control of own
create policy "bookmarks: own" on public.bookmarks for all
  using (user_id = (auth.jwt()->>'sub')) with check (user_id = (auth.jwt()->>'sub'));

-- feedback: anyone can submit, only admins read
create policy "feedback: submit" on public.feedback for insert with check (user_id is null or user_id = (auth.jwt()->>'sub'));
create policy "feedback: admin read" on public.feedback for select using (public.is_admin());
create policy "feedback: admin delete" on public.feedback for delete using (public.is_admin());

-- =====================================================================
-- RPCs
-- =====================================================================

-- Internal: record one answer, update the Mistake Notebook. Returns the effect.
create or replace function public._apply_answer(p_attempt uuid, p_user text, p_qid uuid, p_selected text)
returns text language plpgsql security definer set search_path = public as $$
declare
  v_correct text;
  v_dropped boolean;
  v_effect  text;
  v_existing public.attempt_answers;
begin
  if p_selected is null or p_selected not in ('A','B','C','D','E') then return null; end if;

  select * into v_existing from public.attempt_answers where attempt_id = p_attempt and question_id = p_qid;
  if found then return v_existing.notebook_effect; end if;  -- already recorded (practice mode)

  select correct_option, is_dropped into v_correct, v_dropped from public.questions where id = p_qid;
  if v_correct is null or v_dropped then return null; end if;

  if p_selected = v_correct then
    delete from public.mistakes where user_id = p_user and question_id = p_qid;
    if found then v_effect := 'cleared'; end if;
  else
    if exists (select 1 from public.mistakes where user_id = p_user and question_id = p_qid) then
      update public.mistakes
         set times_missed = times_missed + 1, last_selected = p_selected, last_missed_at = now()
       where user_id = p_user and question_id = p_qid;
      v_effect := 'missed_again';
    else
      insert into public.mistakes (user_id, question_id, last_selected) values (p_user, p_qid, p_selected);
      v_effect := 'added';
    end if;
  end if;

  insert into public.attempt_answers (attempt_id, user_id, question_id, selected_option, is_correct, notebook_effect)
  values (p_attempt, p_user, p_qid, p_selected, p_selected = v_correct, v_effect);
  return v_effect;
end $$;
revoke all on function public._apply_answer(uuid, text, uuid, text) from public, anon, authenticated;

-- Practice mode: lock in one answer immediately.
create or replace function public.record_practice_answer(p_attempt uuid, p_question uuid, p_selected text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  a public.quiz_attempts;
  v_effect text;
  v_correct text;
begin
  select * into a from public.quiz_attempts where id = p_attempt;
  if a.id is null or a.user_id <> (auth.jwt()->>'sub') then raise exception 'Attempt not found'; end if;
  if a.status <> 'in_progress' or a.mode <> 'practice' then raise exception 'Attempt is not an open practice quiz'; end if;
  if not (p_question = any (a.question_ids)) then raise exception 'Question not in this quiz'; end if;

  v_effect := public._apply_answer(p_attempt, a.user_id, p_question, p_selected);
  update public.quiz_attempts
     set responses = responses || jsonb_build_object(p_question::text, jsonb_build_object('selected', p_selected))
   where id = p_attempt;
  select correct_option into v_correct from public.questions where id = p_question;
  return jsonb_build_object('is_correct', p_selected = v_correct, 'correct_option', v_correct, 'effect', v_effect);
end $$;

-- Submit and score a quiz. Exam mode answers are recorded here.
create or replace function public.submit_attempt(p_attempt uuid, p_responses jsonb, p_time_taken int)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  a public.quiz_attempts;
  qid uuid;
  v_correct int; v_wrong int; v_total int; v_score numeric;
begin
  select * into a from public.quiz_attempts where id = p_attempt for update;
  if a.id is null or a.user_id <> (auth.jwt()->>'sub') then raise exception 'Attempt not found'; end if;
  if a.status = 'submitted' then
    return jsonb_build_object('already_submitted', true, 'score', a.score);
  end if;

  foreach qid in array a.question_ids loop
    perform public._apply_answer(p_attempt, a.user_id, qid, p_responses -> qid::text ->> 'selected');
  end loop;

  select count(*) filter (where is_correct), count(*) filter (where not is_correct)
    into v_correct, v_wrong
    from public.attempt_answers where attempt_id = p_attempt;
  v_total := cardinality(a.question_ids);
  v_score := round(v_correct * a.positive_marks - v_wrong * a.negative_marks, 2);

  update public.quiz_attempts set
    responses      = coalesce(p_responses, responses),
    status         = 'submitted',
    submitted_at   = now(),
    time_taken_sec = greatest(0, least(coalesce(p_time_taken, 0), 86400)),
    correct_count  = v_correct,
    wrong_count    = v_wrong,
    skipped_count  = v_total - v_correct - v_wrong,
    total_count    = v_total,
    score          = v_score
  where id = p_attempt;

  return jsonb_build_object('score', v_score, 'correct', v_correct, 'wrong', v_wrong,
                            'skipped', v_total - v_correct - v_wrong, 'total', v_total);
end $$;

-- Build a randomised quiz (dropped questions are always excluded).
create or replace function public.build_quiz(
  p_subject_ids int[] default null,
  p_topic_ids   int[] default null,
  p_exam_ids    int[] default null,
  p_count       int   default 20,
  p_source      text  default 'all',
  p_high_priority_only boolean default false
) returns uuid[] language sql stable security invoker set search_path = public as $$
  select coalesce(array_agg(id), '{}') from (
    select q.id
    from public.questions q
    where not q.is_dropped
      and (p_subject_ids is null or cardinality(p_subject_ids) = 0 or q.subject_id = any (p_subject_ids))
      and (p_topic_ids   is null or cardinality(p_topic_ids)   = 0 or q.topic_id   = any (p_topic_ids))
      and (p_exam_ids    is null or cardinality(p_exam_ids)    = 0 or q.exam_id    = any (p_exam_ids))
      and (
        p_source = 'all'
        or (p_source = 'bookmarks' and exists (select 1 from public.bookmarks b where b.user_id = (auth.jwt()->>'sub') and b.question_id = q.id))
        or (p_source = 'mistakes'  and exists (select 1 from public.mistakes  m where m.user_id = (auth.jwt()->>'sub') and m.question_id = q.id))
      )
      and (not p_high_priority_only or public.high_priority(q))
    order by random()
    limit least(greatest(coalesce(p_count, 20), 1), 150)
  ) s;
$$;

-- How many live questions match a filter (shown in the quiz builder).
create or replace function public.count_questions(
  p_subject_ids int[] default null, p_topic_ids int[] default null, p_exam_ids int[] default null
) returns int language sql stable security invoker set search_path = public as $$
  select count(*)::int from public.questions q
  where not q.is_dropped
    and (p_subject_ids is null or cardinality(p_subject_ids) = 0 or q.subject_id = any (p_subject_ids))
    and (p_topic_ids   is null or cardinality(p_topic_ids)   = 0 or q.topic_id   = any (p_topic_ids))
    and (p_exam_ids    is null or cardinality(p_exam_ids)    = 0 or q.exam_id    = any (p_exam_ids));
$$;

-- Total live PYQs (home page counter)
create or replace function public.get_live_question_count()
returns int language sql stable security definer set search_path = public as $$
  select count(*)::int from public.questions where not is_dropped;
$$;

-- Community stats: % of students who got each question right.
-- Uses each student's FIRST attempt at a question so repeats don't skew it.
create or replace function public.get_question_stats(p_ids uuid[])
returns table (question_id uuid, attempts int, correct int, option_counts jsonb)
language sql stable security definer set search_path = public as $$
  with firsts as (
    select distinct on (user_id, question_id) user_id, question_id, is_correct, selected_option
    from public.attempt_answers
    where question_id = any (p_ids)
    order by user_id, question_id, answered_at
  ), per_opt as (
    select question_id, selected_option, count(*) as n from firsts group by 1, 2
  )
  select f.question_id,
         count(*)::int,
         count(*) filter (where f.is_correct)::int,
         (select jsonb_object_agg(p.selected_option, p.n) from per_opt p where p.question_id = f.question_id)
  from firsts f
  group by f.question_id;
$$;

-- Student's own accuracy by subject/topic (heat map)
create or replace function public.get_my_accuracy()
returns table (subject_id int, topic_id int, attempted int, correct int)
language sql stable security invoker set search_path = public as $$
  select q.subject_id, q.topic_id, count(*)::int, count(*) filter (where aa.is_correct)::int
  from public.attempt_answers aa
  join public.questions q on q.id = aa.question_id
  where aa.user_id = (auth.jwt()->>'sub')
  group by q.subject_id, q.topic_id;
$$;

-- Mistake counts per subject/topic (notebook dashboard)
create or replace function public.get_my_mistake_summary()
returns table (subject_id int, topic_id int, mistakes int, high_priority int)
language sql stable security invoker set search_path = public as $$
  select q.subject_id, q.topic_id, count(*)::int, count(*) filter (where public.high_priority(q))::int
  from public.mistakes m
  join public.questions q on q.id = m.question_id
  where m.user_id = (auth.jwt()->>'sub')
  group by q.subject_id, q.topic_id;
$$;

-- Admin analytics
create or replace function public.admin_analytics()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_today date := (now() at time zone 'Asia/Kolkata')::date;
  v_min int;
  result jsonb;
begin
  if not public.is_admin() then raise exception 'Admins only'; end if;
  select min_stats_attempts into v_min from public.app_settings where id = 1;

  select jsonb_build_object(
    'total_users',      (select count(*) from public.profiles),
    'new_users_7d',     (select count(*) from public.profiles where created_at > now() - interval '7 days'),
    'live_questions',   (select count(*) from public.questions where not is_dropped),
    'dropped_questions',(select count(*) from public.questions where is_dropped),
    'quizzes_submitted',(select count(*) from public.quiz_attempts where status = 'submitted'),
    'answers_recorded', (select count(*) from public.attempt_answers),
    'dau_today', (select count(distinct user_id) from public.quiz_attempts
                  where (updated_at at time zone 'Asia/Kolkata')::date = v_today),
    'dau_series', (
      select coalesce(jsonb_agg(jsonb_build_object('day', d::date, 'users', coalesce(u.n, 0)) order by d), '[]'::jsonb)
      from generate_series(v_today - 13, v_today, interval '1 day') d
      left join (
        select (updated_at at time zone 'Asia/Kolkata')::date as day, count(distinct user_id) as n
        from public.quiz_attempts group by 1
      ) u on u.day = d::date
    ),
    'most_missed', (
      select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) from (
        select q.id, left(regexp_replace(q.question_en, '<[^>]+>', ' ', 'g'), 160) as question,
               s.name_en as subject, count(*) as attempts,
               round(100.0 * count(*) filter (where aa.is_correct) / count(*), 1) as correct_pct
        from public.attempt_answers aa
        join public.questions q on q.id = aa.question_id
        join public.subjects s on s.id = q.subject_id
        group by q.id, s.name_en
        having count(*) >= greatest(v_min, 1)
        order by correct_pct asc, attempts desc
        limit 15
      ) t
    ),
    'feedback_count', (select count(*) from public.feedback)
  ) into result;
  return result;
end $$;

grant execute on function public.get_live_question_count() to anon, authenticated;
grant execute on function public.get_question_stats(uuid[]) to anon, authenticated;
grant execute on function public.build_quiz(int[], int[], int[], int, text, boolean) to anon, authenticated;
grant execute on function public.count_questions(int[], int[], int[]) to anon, authenticated;
